# Generated by Django 4.2 on 2023-04-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodify_API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
