# Generated by Django 4.2 on 2023-04-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodify_API', '0002_rename_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='settlement',
        ),
        migrations.AddField(
            model_name='user',
            name='settlement',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
