# Generated by Django 4.2 on 2023-05-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodify_API', '0005_rename_phone_number_order_receiver_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Processing', max_length=20),
        ),
    ]
